### PR TITLE
doc(readme): add image and reference

### PR DESCRIPTION
**Pull request by felipehuerta17**
These commits:

- Convert the image into .HTML to resize them to a proper scale
- Add an explicit reference to the Authors of SIR-X below the figure

### CODE REVIEW

**Comment by jia200x** [comment]
please, rebase against the latest version of this branch. There's a commit that's already present in the original branch and that's why it fails.

**Comment by jia200x** [comment]
This is the last commit of the branch: dda1cc02cb0071c05508c4190d883e4d9cf1d646

**Comment by felipehuerta17** [comment]
@jia200x done

**Comment by felipehuerta17** [comment]
@jia200x now is sorted!

**Pull request merged**
